version: '2'

services:
  php:
    build:
      context: ./docker/php7-fpm
    image: laravel:php-fpm
    container_name: php
    environment:
      MAILCATCHER_HOST: 'mailcatcher'
      MYSQL_HOST: 'mysql'
      DEBUG: 'true'
    volumes:
      - ./app/:/var/www/html:rw

  mailcatcher:
    image: tophfr/mailcatcher
    container_name: mailcatcher
    environment:
      MAIL_HOST: mailcatcher
      MAIL_PORT: 1025
    ports:
      - 1080:80
      - 1025:1025

  web:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: root
    ports:
      - 3306:3306

volumes:
  data: